#!/bin/bash

# Save trace setting
NEC_XTRACE=$(set +o | grep xtrace)
set +o xtrace

# source $TOP_DIR/lib/neutron_plugins/ovs_base
source $TOP_DIR/lib/neutron_plugins/openvswitch_agent

# The followig functions are from the above openvswitch_agent.
# If some change is needed, let's redefine the function.
#
# neutron_plugin_create_nova_conf
# neutron_plugin_install_agent_packages
# neutron_plugin_configure_debug_command
# neutron_plugin_configure_dhcp_agent
# neutron_plugin_configure_l3_agent
# neutron_plugin_configure_plugin_agent
# neutron_plugin_setup_interface_driver
# neutron_plugin_check_adv_test_requirements

# Neutron-server functions required by devstack neutron plugin interfaces.

function neutron_plugin_configure_common {
    Q_PLUGIN_CONF_PATH=etc/neutron/plugins/nec
    Q_PLUGIN_CONF_FILENAME=necnwa.ini
    Q_PLUGIN_CLASS="necnwa"
    # Temporary use neutron L3RouterPlugin
    Q_SERVICE_PLUGIN_CLASSES="router"
    # Q_SERVICE_PLUGIN_CLASSES="necnwa_router"
    local plugin_conf_src_abspath=${NETWORKING_NEC_DIR}/${Q_PLUGIN_CONF_PATH}
    local plugin_conf_sys_abspath=/${Q_PLUGIN_CONF_PATH}
    cp ${q_plugin_conf_abspath}/${Q_PLUGIN_CONF_FILENAME} ${plugin_conf_sys_abspath}/
    cp ${q_plugin_conf_abspath}/resource_group.json ${plugin_conf_sys_abspath}/
    chmod 0644 /${Q_PLUGIN_CONF_PATH}/${Q_PLUGIN_CONF_FILENAME}
}

function neutron_plugin_configure_service {
    iniset $NEUTRON_CONF DEFAULT api_extensions_path neutron/plugins/nec/extensions/
    iniset /$Q_PLUGIN_CONF_FILE NWA ServerURL $NECNWA_SERVER_URL
    iniset /$Q_PLUGIN_CONF_FILE NWA AccessKeyId $NECNWA_ACCESS_KEY_ID
    iniset /$Q_PLUGIN_CONF_FILE NWA SecretAccessKey $NECNWA_SECRET_ACCESS_KEY
}

# NEC plugin specific functions

function start_nwa_agent {
    run_process nwa-agt "$NEUTRON_BIN_DIR/neutron-necnwa-agent --config-file $NEUTRON_CONF --config-file /$Q_PLUGIN_CONF_FILE"
}

# Restore xtrace
$NEC_XTRACE
