#!/bin/bash

NECNWA_SERVER_URL=${NECNWA_SERVER_URL:-}
NECNWA_ACCESS_KEY_ID=${NECNWA_ACCESS_KEY_ID:-}
NECNWA_SECRET_ACCESS_KEY=${NECNWA_SECRET_ACCESS_KEY:-}
NECNWA_USE_NECNWA_ROUTER=${NECNWA_USE_NECNWA_ROUTER:-True}
NECNWA_L3_PLUGIN=${NECNWA_L3_PLUGIN:-"necnwa_router"}

# In addition to the above, you can use configurartion options
# used in devstack/lib/neutron_plugins/openvswitch_agent.
