#!/bin/bash

NECNWA_SERVER_URL=${NECNWA_SERVER_URL:-}
NECNWA_ACCESS_KEY_ID=${NECNWA_ACCESS_KEY_ID:-}
NECNWA_SECRET_ACCESS_KEY=${NECNWA_SECRET_ACCESS_KEY:-}

# In addition to the above, you can use configurartion options
# used in devstack/lib/neutron_plugins/openvswitch_agent.
